apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      repository: "traefik"
      tag: "3.1.2"
    additionalArguments:
      - "--certificatesresolvers.myresolver.tailscale=true"